### ISSUE TITLE
some question about notation

### ISSUE THREAD

**Issue by ChenDRAG** [mattloper/opendr#24]
hi i'd like to ask that what does
dterms = 'v', 'rt', 't', 'f', 'c', 'k' 
in
class ProjectPoints(Ch):  
means
and hopefully could you please  tell me how to look up for the reference book?because currently i can only find 2 tutorials?
thanks.

**Comment by A7ocin** [comment]
Hello @ChenDRAG 
I have the same doubt, did you manage to find some explainations?
Thank you

**Comment by thmoa** [comment]
v: vertices
t: translation
rt: rotation

camera:
https://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#projectpoints

**Comment by A7ocin** [comment]
Thank you @thmoa!
