### ISSUE TITLE
Retrieve visible vertices

### ISSUE THREAD

**Issue by vladsterz** [mattloper/opendr#32]
Not really an issue, more of a question. Is there a way to retrieve the visible from a given viewpoint vertices?

**Comment by krips89** [comment]
Solution?

**Comment by vladsterz** [comment]
Hey. If I remember correctly I was only to find visible faces.

**Comment by welch** [comment]
late to the party, but here's how to get visible vertex indices from an opendr renderer
(any of the derived renderer classes should work for this):
```
def visible_vidxs(rn):
    """given renderer rn, return a list of visible vertex indices"""
    visible_fidxs = np.unique(rn.visibility_image[rn.visibility_image != 4294967295])
    visible_vidxs = np.unique(rn.f[visible_fidxs].ravel())
    return visible_vidxs
```
